name: CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Valgrind
              run: |
                  sudo apt update
                  sudo apt install -y valgrind

            - name: Build Application
              run: make

            - name: Run Server with Valgrind
              run: |
                  valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes ./server &
                  SERVER_PID=$!
                  sleep 5
                  kill -SIGTERM $SERVER_PID
                  wait $SERVER_PID
